export const APIUrls = {
    baseURL: 'http://localhost:5000',
    baseGetImage: 'http://localhost:5000/images',
    register: '/api/register',
    login: '/api/login',
    logout: '/api/logout',
    fileUpload: '/api/file-upload',
    images: '/api/images',
    addPost: '/api/add',
    editPost: '/api/edit',
    post: '/api/post',
    posts: '/api/posts',
    refreshTokens: '/api/refresh-tokens',
    forgotPassword: '/api/forgot-password',
    resetPassword: '/api/reset-password',
    emailActivation: '/api/email-activation',
    repeatEmailActivation: '/api/repeat-email',
    googleLogin: '/api/google-login',
    facebookLogin: '/api/facebook-login'
};
