export const APIUrls = {
    baseURL: 'http://localhost:5000',
    baseGetImage: 'http://localhost:5000/images',
    register: '/register',
    login: '/login',
    logout: '/logout',
    fileUpload: '/file-upload',
    images: '/images',
    homePage: '/',
    addPost: '/add',
    editPost: '/edit',
    post: '/post',
    posts: '/posts',
    learnMaterialUI: '/learn',
    refreshTokens: '/refresh-tokens',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    emailActivation: '/email-activation',
    repeatEmailActivation: '/repeat-email',
    googleLogin: '/google-login',
    facebookLogin: '/facebook-login',
    notfound: '/notfound',
};
