export const RoutesUrls = {
    register: '/register',
    login: '/login',
    logout: '/logout',
    fileUpload: '/content',
    images: '/pictures',
    homePage: '/',
    addPost: '/add',
    editPost: '/edit',
    post: '/post',
    posts: '/posts',
    refreshTokens: '/refresh-tokens',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    emailActivation: '/email-activation',
    repeatEmailActivation: '/repeat-email',
    googleLogin: '/google-login',
    facebookLogin: '/facebook-login',
    notfound: '/notfound',
};